//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSProfessional.SharePoint.WebParts.Navigation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPSProfessional_SharePoint_WebParts_Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPSProfessional_SharePoint_WebParts_Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPSProfessional.SharePoint.WebParts.Navigation.Resources.SPSProfessional.SharePoi" +
                            "nt.WebParts.Navigation", typeof(SPSProfessional_SharePoint_WebParts_Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Can&apos;t open {0}.
        /// </summary>
        internal static string SPS_Err_Open_Url {
            get {
                return ResourceManager.GetString("SPS_Err_Open_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour:.
        /// </summary>
        internal static string SPSPE_Behaviour {
            get {
                return ResourceManager.GetString("SPSPE_Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        internal static string SPSPE_Filter {
            get {
                return ResourceManager.GetString("SPSPE_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter List:.
        /// </summary>
        internal static string SPSPE_FilterList {
            get {
                return ResourceManager.GetString("SPSPE_FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter web:.
        /// </summary>
        internal static string SPSPE_FilterWeb {
            get {
                return ResourceManager.GetString("SPSPE_FilterWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow ListView.
        /// </summary>
        internal static string SPSPE_FollowListView {
            get {
                return ResourceManager.GetString("SPSPE_FollowListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the folder currently selected in the view..
        /// </summary>
        internal static string SPSPE_FollowListViewTip {
            get {
                return ResourceManager.GetString("SPSPE_FollowListViewTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide underscore folders.
        /// </summary>
        internal static string SPSPE_HideUnderScoreFolders {
            get {
                return ResourceManager.GetString("SPSPE_HideUnderScoreFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide folders that begins with _.
        /// </summary>
        internal static string SPSPE_HideUnderScoreFoldersTip {
            get {
                return ResourceManager.GetString("SPSPE_HideUnderScoreFoldersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked to:.
        /// </summary>
        internal static string SPSPE_LinkedTo {
            get {
                return ResourceManager.GetString("SPSPE_LinkedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max levels:.
        /// </summary>
        internal static string SPSPE_MaxLevels {
            get {
                return ResourceManager.GetString("SPSPE_MaxLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to list.
        /// </summary>
        internal static string SPSPE_NavigateToList {
            get {
                return ResourceManager.GetString("SPSPE_NavigateToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to list folder..
        /// </summary>
        internal static string SPSPE_NavigateToListTip {
            get {
                return ResourceManager.GetString("SPSPE_NavigateToListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to list view.
        /// </summary>
        internal static string SPSPE_NavigateToListView {
            get {
                return ResourceManager.GetString("SPSPE_NavigateToListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file counter.
        /// </summary>
        internal static string SPSPE_ShowFileCounter {
            get {
                return ResourceManager.GetString("SPSPE_ShowFileCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Folders.
        /// </summary>
        internal static string SPSPE_ShowFolders {
            get {
                return ResourceManager.GetString("SPSPE_ShowFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lists.
        /// </summary>
        internal static string SPSPE_ShowLists {
            get {
                return ResourceManager.GetString("SPSPE_ShowLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show subsites.
        /// </summary>
        internal static string SPSPE_ShowSubsites {
            get {
                return ResourceManager.GetString("SPSPE_ShowSubsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root web url:.
        /// </summary>
        internal static string SPSPE_TopUrl {
            get {
                return ResourceManager.GetString("SPSPE_TopUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree expand depth:.
        /// </summary>
        internal static string SPSPE_TreeExpandDepth {
            get {
                return ResourceManager.GetString("SPSPE_TreeExpandDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the number of files in each folder, only available in doclibs..
        /// </summary>
        internal static string SPSPR_ShowFileCounterTip {
            get {
                return ResourceManager.GetString("SPSPR_ShowFileCounterTip", resourceCulture);
            }
        }
    }
}
